### ISSUE TITLE
Bot options

### ISSUE THREAD

**Issue by Thaxtin** [Macx-Lio/MultiBot#9]
Would it be possible to add options to created bots similar to the alt bots where the trees pop out left and right?

**Comment by Macx-Lio** [comment]
Hello Thaxtin,

there are currently no Commands from Mod-Playerbot that allow you to adjust Skin-Color, Hair, etc.
You should add your wish as Idea in this Forum: https://github.com/liyunfan1223/mod-playerbots/discussions
Maybe you are lucky and they add such a Function to Mod-Playerbot.
Then I would be able to build such a Interface.

Have Fun :D
